"""
Django settings for harpreet_singh project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lt6&9x040^zmg89z8!q_#(%s(7jr@3umkzrx!89)wmi-wgjxcd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("debug")

ALLOWED_HOSTS = ["*"]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "contact",
    'django_ckeditor_5',
    "Blog",
    "ckeditor",
    "Pdf_management",
    "PropertyValuation"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'harpreet_singh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'harpreet_singh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'  # Set German time zone

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "kartikprajapati26122004@gmail.com"
EMAIL_HOST_PASSWORD = "lcza wsye liez ddkk"


STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static'),
]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'underline', '|', 
            'fontColor', 'fontBackgroundColor', 'fontSize', '|', 'bulletedList', 'numberedList', '|', 
            'undo', 'redo', '|', 'sourceEditing'  # Add sourceEditing button
        ],
        'fontColor': {
            'colors': [
                {'color': 'black', 'label': 'Black'},
                {'color': 'red', 'label': 'Red'},
                {'color': 'green', 'label': 'Green'},
                {'color': 'blue', 'label': 'Blue'},
                {'color': 'yellow', 'label': 'Yellow'},
            ]
        },
        'fontBackgroundColor': {
            'colors': [
                {'color': 'black', 'label': 'Black'},
                {'color': 'red', 'label': 'Red'},
                {'color': 'green', 'label': 'Green'},
                {'color': 'blue', 'label': 'Blue'},
                {'color': 'yellow', 'label': 'Yellow'},
            ]
        },
        'fontSize': {
            'options': ['default', 'small', 'big'],
        },
        'simpleUpload': {
            'uploadUrl': '/media/',  # This URL handles image uploads
            'headers': {
                'X-CSRFToken': '{{ csrf_token }}',  # Ensure CSRF token is included
            }
        },
        'defaultColor': 'black',
        
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
        'imageStyle:alignLeft', 
        'imageStyle:alignCenter',
        'imageStyle:alignRight'
            ],
        },
        
        'height': 300,
        'width': '100%',
    },
}

MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_5_CUSTOM_CSS = 'css/ckeditor.css'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'kartikprajapati26122004@gmail.com'
# EMAIL_HOST_PASSWORD = 'lcza wsye liez ddkk'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'harpreet_singh.email_backend.UnsafeEmailBackend'

EMAIL_HOST = 'smtpout.secureserver.net'     # or smtp.secureserver.net
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'info@ghotra-immobilien.com'
EMAIL_HOST_PASSWORD = 'K@rtik1234123'
DEFAULT_FROM_EMAIL = 'info@ghotra-immobilien.com'
# SEND_EMAIL=kartikprajapati26122004@gmail.com
# SEND_EMAIL_PASSWORD=lcza wsye liez ddkk
# DEFAULT_FROM_EMAIL = 'Property Valuation <your_email@gmail.com>'
