# Generated by Django 5.1.4 on 2025-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValuationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='PropertyValuationFile')),
            ],
            options={
                'verbose_name': 'Property_Valuation_File',
                'verbose_name_plural': 'Property_Valuation_File',
            },
        ),
        migrations.CreateModel(
            name='PropertyValuationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('apartment_price_per_meter_square', models.CharField(blank=True, max_length=10, null=True)),
                ('house_price_per_meter_square', models.CharField(blank=True, max_length=10, null=True)),
                ('plot_price_per_meter_square', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Property_valuation',
                'verbose_name_plural': 'Property_valuation',
            },
        ),
    ]
