# Generated by Django 5.1.4 on 2025-07-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyValuation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyvaluationfile',
            old_name='File',
            new_name='file',
        ),
    ]
