# Generated by Django 5.1.4 on 2025-01-09 04:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('blog_image', models.ImageField(upload_to='blog_image')),
            ],
        ),
    ]
