# Generated by Django 5.1.4 on 2025-07-10 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pdf_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmanagement',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfmanagement',
            name='pdf_file',
            field=models.FileField(upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
